<%--<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Administrator_Default" %>--%>
<%@ Page Language="C#" MasterPageFile="~/Master/Dizajn.Master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Administrator_Default" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="mainContent" runat="server">
    <form id="form1" runat="server">
    <p>
        Pozdravljen&nbsp;
        <asp:Label ID="LabelUserName2" runat="server" Text="NOT HERE"></asp:Label>
        &nbsp;(admin)
        !</p>
    <asp:Label ID="Label2" runat="server" ForeColor="Red"></asp:Label>
    <asp:Panel ID="PanelConfirm" runat="server" Height="65px" Visible="False" 
        Width="274px">
        Ali želiš res izbrisati uporabnika
        <asp:Label ID="LabelUserName" runat="server" Text="NOT HERE"></asp:Label>
        ?<br />
        <asp:Button ID="ButtonYes" runat="server" Height="24px" Text="Da" 
            onclick="ButtonYes_Click" />
        <asp:Button ID="ButtonNo" runat="server" Height="24px" Text="No" 
            onclick="ButtonNo_Click" />
    </asp:Panel>
    <br />
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" onrowdeleting="RowDelete" 
            onrowediting="RowEdit" AutoGenerateColumns="False">
            <Columns>
                <asp:BoundField DataField="UserName" HeaderText="Uporabniki" />
                <asp:BoundField DataField="Email" HeaderText="Email" />
                <asp:BoundField DataField="LastLoginDate" HeaderText="ZadnjiDatumPrijave" />
                <asp:CheckBoxField DataField="IsOnline" HeaderText="Online" />
                <asp:CheckBoxField DataField="IsApproved" HeaderText="Potrjen" />
            </Columns>
        </asp:GridView>
    
    </div>
    
    
    <p>
        <asp:Label ID="Label1" runat="server" Text="Dodaj uporabnika:  "></asp:Label>
        <asp:Button ID="Dodaj" runat="server" Text="Dodaj" onclick="Dodaj_Click" />
    </p>
    <p>
    <asp:LoginStatus ID="LoginStatus1" runat="server" 
            onloggingout="LoginStatus1_LoggingOut" LoginText="Prijavi" 
            LogoutText="Odjavi" />
    </p>
    </form>
</asp:Content>
